name: tests-orders

on:
  pull_request: # on open, sync, re-open a PR AND files inside orders/** has changed then only run this suite
    paths:
      - 'orders/**'
  
jobs:
  build:
    runs-on: ubuntu-latest #specify machine
    steps:
      - uses: actions/checkout@v2 #take code out of our project
      - run: cd orders && npm install && npm run test:ci #run tests for orders service "add a CI script inside package.json so that it runs only once and doesnt watch for changes"
      
    
