name: tests-payments

on:
  pull_request: # on open, sync, re-open a PR AND files inside payments/** has changed then only run this suite
    paths:
      - 'payments/**'
  
jobs:
  build:
    runs-on: ubuntu-latest #specify machine
    steps:
      - uses: actions/checkout@v2 #take code out of our project
      - run: cd payments && npm install && npm run test:ci #run tests for payments service "add a CI script inside package.json so that it runs only once and doesnt watch for changes"
      
    
