apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-depl
spec:
  replicas: 1
  selector: #tell which pods to get access to
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
    spec:
      containers:
        - name: tickets-mongo
          image: mongo #standard image present in docker hub
          # image: asia.gcr.io/ticketing-dev-315817/mongo DONT USE THIS
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
spec:
  selector: #tell which pods to get access to
    app: tickets-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
